-- ==============================================================================
-- AI_Book College Notes & Material Repository - PostgreSQL / Supabase Setup Script
-- Project ID: udsvohrfzzeanqnjfazb
-- Compatible with: Supabase PostgreSQL (Postgres 15+)
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. REGISTRATIONS TABLE
-- Stores all student and faculty/professor registrations
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.registrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'faculty', 'admin')),
    branch TEXT DEFAULT 'Computer Science',
    semester INTEGER DEFAULT 1 CHECK (semester BETWEEN 1 AND 8),
    roll_number TEXT DEFAULT '', -- Roll Number (students) or Employee ID (faculty)
    avatar_url TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 3. PROFILES TABLE
-- Profile records visible in Supabase Table Editor
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'faculty', 'admin')),
    branch TEXT DEFAULT 'Computer Science',
    semester INTEGER DEFAULT 1,
    roll_number TEXT DEFAULT '',
    avatar_url TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Make sure profiles is flexible and doesn't reject direct registration inserts
ALTER TABLE public.profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- ==============================================================================
-- 4. CURRICULUM SUBJECTS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    branch TEXT NOT NULL,
    semester INTEGER NOT NULL CHECK (semester BETWEEN 1 AND 8),
    description TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 5. MATERIALS TABLE (Lecture Notes & PYQs)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('note', 'pyq')),
    subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
    semester INTEGER NOT NULL CHECK (semester BETWEEN 1 AND 8),
    branch TEXT NOT NULL,
    academic_year TEXT DEFAULT '2024-25',
    module_unit TEXT DEFAULT 'Unit 1',
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size TEXT DEFAULT '1.5 MB',
    file_type TEXT DEFAULT 'application/pdf',
    description TEXT DEFAULT '',
    uploader_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    uploader_name TEXT NOT NULL DEFAULT 'Faculty Member',
    downloads_count INTEGER DEFAULT 0,
    views_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 6. STUDENT BOOKMARKS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    material_id BIGINT NOT NULL REFERENCES public.materials(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, material_id)
);

-- ==============================================================================
-- 7. QUIZ PRACTICE & PERFORMANCE HISTORY TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.quiz_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    subject_name TEXT NOT NULL,
    topic TEXT NOT NULL,
    score INTEGER NOT NULL,
    total_questions INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- 8. PERFORMANCE INDEXES
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_registrations_email ON public.registrations(email);
CREATE INDEX IF NOT EXISTS idx_registrations_role ON public.registrations(role);
CREATE INDEX IF NOT EXISTS idx_registrations_branch_sem ON public.registrations(branch, semester);

CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

CREATE INDEX IF NOT EXISTS idx_materials_subject_id ON public.materials(subject_id);
CREATE INDEX IF NOT EXISTS idx_materials_type ON public.materials(type);
CREATE INDEX IF NOT EXISTS idx_materials_branch_semester ON public.materials(branch, semester);

CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON public.bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_quiz_history_user ON public.quiz_history(user_id);

-- ==============================================================================
-- 9. ROW LEVEL SECURITY (RLS) POLICIES
-- Ensures data can be read and written without blocking legitimate operations
-- ==============================================================================
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_history ENABLE ROW LEVEL SECURITY;

-- Registrations Policies: Allow insert, select, and updates
DROP POLICY IF EXISTS "Allow anon and auth inserts to registrations" ON public.registrations;
DROP POLICY IF EXISTS "Allow public anon inserts" ON public.registrations;
CREATE POLICY "Allow anon and auth inserts to registrations"
    ON public.registrations FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read on registrations" ON public.registrations;
DROP POLICY IF EXISTS "Allow public anon reads" ON public.registrations;
CREATE POLICY "Allow public read on registrations"
    ON public.registrations FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow update own registration" ON public.registrations;
DROP POLICY IF EXISTS "Allow anon and auth update to registrations" ON public.registrations;
CREATE POLICY "Allow anon and auth update to registrations"
    ON public.registrations FOR UPDATE
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon and auth delete to registrations" ON public.registrations;
CREATE POLICY "Allow anon and auth delete to registrations"
    ON public.registrations FOR DELETE
    USING (true);

-- Profiles Policies: Allow read, insert, and update
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Allow public read on profiles" ON public.profiles;
CREATE POLICY "Allow public read on profiles"
    ON public.profiles FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Allow anon insert to profiles" ON public.profiles;
CREATE POLICY "Allow anon insert to profiles"
    ON public.profiles FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update to profiles" ON public.profiles;
CREATE POLICY "Allow anon update to profiles"
    ON public.profiles FOR UPDATE
    USING (true)
    WITH CHECK (true);

-- Subjects, Materials & Bookmarks Policies
DROP POLICY IF EXISTS "Anyone can read subjects" ON public.subjects;
CREATE POLICY "Anyone can read subjects" ON public.subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Anyone can read materials" ON public.materials;
CREATE POLICY "Anyone can read materials" ON public.materials FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can upload materials" ON public.materials;
CREATE POLICY "Authenticated users can upload materials" ON public.materials FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can manage own bookmarks" ON public.bookmarks;
CREATE POLICY "Users can manage own bookmarks" ON public.bookmarks FOR ALL USING (true);

DROP POLICY IF EXISTS "Users can manage own quiz history" ON public.quiz_history;
CREATE POLICY "Users can manage own quiz history" ON public.quiz_history FOR ALL USING (true);

-- ==============================================================================
-- 10. AUTO-SYNC TRIGGER: REGISTRATIONS -> PROFILES
-- When a user registers in registrations table, automatically syncs to profiles!
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.sync_registration_to_profile()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        name,
        email,
        role,
        branch,
        semester,
        roll_number,
        avatar_url,
        created_at,
        updated_at
    )
    VALUES (
        COALESCE(NEW.auth_user_id, NEW.id),
        NEW.name,
        NEW.email,
        NEW.role,
        COALESCE(NEW.branch, 'Computer Science'),
        COALESCE(NEW.semester, 1),
        COALESCE(NEW.roll_number, ''),
        COALESCE(NEW.avatar_url, ''),
        NEW.created_at,
        NEW.updated_at
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        email = EXCLUDED.email,
        role = EXCLUDED.role,
        branch = EXCLUDED.branch,
        semester = EXCLUDED.semester,
        roll_number = EXCLUDED.roll_number,
        updated_at = NOW();

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_registration_to_profile ON public.registrations;
CREATE TRIGGER trg_sync_registration_to_profile
    AFTER INSERT OR UPDATE ON public.registrations
    FOR EACH ROW EXECUTE FUNCTION public.sync_registration_to_profile();

-- ==============================================================================
-- 11. AUTO-TRIGGER FROM SUPABASE AUTH (auth.users)
-- Syncs user credentials from Supabase Auth into both registrations & profiles
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.registrations (
        auth_user_id,
        name,
        email,
        role,
        branch,
        semester,
        roll_number,
        created_at,
        updated_at
    )
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'role', 'student'),
        COALESCE(NEW.raw_user_meta_data->>'branch', 'Computer Science'),
        COALESCE((NEW.raw_user_meta_data->>'semester')::integer, 1),
        COALESCE(NEW.raw_user_meta_data->>'roll_number', ''),
        NOW(),
        NOW()
    )
    ON CONFLICT (email) DO UPDATE SET
        auth_user_id = EXCLUDED.auth_user_id,
        name = EXCLUDED.name,
        role = EXCLUDED.role,
        branch = EXCLUDED.branch,
        semester = EXCLUDED.semester,
        roll_number = EXCLUDED.roll_number,
        updated_at = NOW();

    INSERT INTO public.profiles (
        id,
        name,
        email,
        role,
        branch,
        semester,
        roll_number,
        created_at,
        updated_at
    )
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'role', 'student'),
        COALESCE(NEW.raw_user_meta_data->>'branch', 'Computer Science'),
        COALESCE((NEW.raw_user_meta_data->>'semester')::integer, 1),
        COALESCE(NEW.raw_user_meta_data->>'roll_number', ''),
        NOW(),
        NOW()
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        role = EXCLUDED.role,
        branch = EXCLUDED.branch,
        semester = EXCLUDED.semester,
        roll_number = EXCLUDED.roll_number,
        updated_at = NOW();

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- ==============================================================================
-- 12. BACKFILL ALL EXISTING REGISTRATIONS INTO PROFILES
-- ==============================================================================
INSERT INTO public.profiles (id, name, email, role, branch, semester, roll_number, avatar_url, created_at, updated_at)
SELECT id, name, email, role, branch, semester, roll_number, avatar_url, created_at, updated_at
FROM public.registrations
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    branch = EXCLUDED.branch,
    semester = EXCLUDED.semester,
    roll_number = EXCLUDED.roll_number;

-- ==============================================================================
-- 13. SEED CURRICULUM SUBJECTS
-- ==============================================================================
INSERT INTO public.subjects (code, name, branch, semester, description)
VALUES 
    ('CS401', 'Operating Systems', 'Computer Science', 4, 'Processes, Threads, CPU Scheduling, Concurrency, Virtual Memory and File Systems.'),
    ('CS402', 'Database Management Systems', 'Computer Science', 4, 'ER Model, Relational Algebra, SQL, Normalization, ACID Transactions, Indexing.'),
    ('CS403', 'Computer Architecture', 'Computer Science', 4, 'Instruction Set Architecture, Pipelining, Memory Hierarchy, Cache and I/O Organization.'),
    ('CS301', 'Data Structures & Algorithms', 'Computer Science', 3, 'Arrays, Linked Lists, Stacks, Queues, Trees, Graphs, Sorting, Dynamic Programming.'),
    ('CS501', 'Computer Networks', 'Computer Science', 5, 'OSI & TCP/IP layers, routing protocols, flow control, congestion, DNS, HTTP/HTTPS.'),
    ('CS601', 'Machine Learning', 'Computer Science', 6, 'Supervised and Unsupervised Learning, Regression, Classification, Neural Networks.'),
    ('CS101', 'Programming in C', 'Computer Science', 1, 'Pointers, structures, file handling, memory management, foundational problem solving.'),
    ('MATH101', 'Engineering Mathematics I', 'Computer Science', 1, 'Calculus, Linear Algebra, Matrices, Eigenvalues, Vector spaces.'),
    ('EC301', 'Digital Electronics', 'Electronics', 3, 'Boolean logic, logic gates, combinational and sequential circuit design, flip-flops.'),
    ('IT502', 'Web Technologies', 'Information Technology', 5, 'Full-stack development, HTTP protocols, REST APIs, client-server models, security.')
ON CONFLICT (code) DO NOTHING;
